Import('env')

CPP_FILES = [
    'BooleanVariable.cpp',
    'Clause.cpp',
    'FactorNode.cpp',
    'Literal.cpp',
    'GenerateOptions.cpp',
    'ProgramArguments.cpp',
    'RandomKSatFormula.cpp',
    'satpi.cpp',
    'VariableNode.cpp'
  ]

env.Append(CPPPATH=['../'])
env.Program('satpi', CPP_FILES, LIBS=[], LIBPATH=[])
